---
image: docker:19.03-git

services:
  - docker:19.03-dind

include:
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-login.yml

build:
  script:
    - docker build -t lansible/docker-dind-buildx:latest .
    - docker push lansible/docker-dind-buildx:latest
